### Biblioteca [**NumPy**](https://numpy.org/doc/stable/index.html)
<br>
<center><img src="https://i.imgur.com/dZ1XE9o.png" width=400></center>

NumPy (*Numerical Python*) es una biblioteca que proporciona una forma eficiente de trabajar con arreglos de datos numéricos en Python.

El tipo de dato principal de Numpy es el `ndarray`. El **ndarray** es un tipo de dato _homogéneo_ y _n-dimensional_.

Una lista de python o un DataFrame de pandas (como veremos más adelante), pueden contener diferentes tipos de datos. Que un `ndarray` sea **homogéneo** implica que todos sus datos sean del mismo tipo, por ejemplo de tipo flotantes. Y **n-dimensional** significa que se puede trabajar con cualquier dimensión, desde una dimensión (vectores), 2 dimensiones (matrices) o un grupo de matrices apiladas (n dimensiones).

Ahora importamos `numpy`. Por convención se importa como `np`

In [1]:
import numpy as np

##### Vectores
Los vectores son arreglos de NumPy unidimensionales y se ven así:

In [2]:
# Creación de un arreglo unidimensional con valores enteros del 0 al 4
arreglo = np.array([0, 1, 2, 3, 4])
print("Arreglo:", arreglo)

# Tipo de dato ndarray
print(type(arreglo))

Arreglo: [0 1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
#Podemos ver que arreglo es unimensional mirando su forma
arreglo.shape

(5,)

In [4]:
#Número de dimensiones
arreglo.ndim

1

In [5]:
#Número de elementos
arreglo.size

5

In [6]:
arreglo.dtype

dtype('int64')

se usa la función [rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html) disponible en el módulo `random` de NumPy para crear arreglos inicializados con valores aleatorios entre 0  y 1.

In [7]:
# Otro ejemplo de arreglo con datos numéricos pero generados aleatoriamente
arreglo2 = np.random.rand(5) # no incluye 1
print(arreglo2)
print(arreglo2.shape)

[0.81101007 0.46313699 0.45695313 0.27150323 0.41521633]
(5,)


In [8]:
arreglo2.dtype

dtype('float64')

Para generar arreglos con números enteros aleatorios usamos la función [randint](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html#numpy.random.randint)

In [19]:
arreglo3 = np.random.randint(low=1, high=20, size=10)
print(arreglo3)
print(arreglo3.shape)

[13  3 10  4 13  8 17  9  9 11]
(10,)


Podemos acceder a los elementos de un `ndarray` similar a como lo hacíamos en las listas de python, usando indexación

In [20]:
print(arreglo3[2])

10


In [21]:
arreglo3[::2]

array([13, 10, 13, 17,  9])

In [22]:
#Obtengo los 3 últimos elementos de mi_arreglo
arreglo3[-3:]

array([ 9,  9, 11])

In [23]:
#cuidado al modificar
a = arreglo3[::2].copy() #usar copy() para no modificar el arreglo original
print(a)

[13 10 13 17  9]


In [24]:
a[3] = 0
print(a)
arreglo3

[13 10 13  0  9]


array([13,  3, 10,  4, 13,  8, 17,  9,  9, 11])

#### Formas alternativas de crear arreglos

In [25]:
# np.arange() similar al range() de python
mi_arreglo1 = np.arange(10,30,1)
mi_arreglo1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [29]:
# uso de .linspace() para crear un vector de 9 elementos equiespaciados entre 0 y 100 (ambos incluidos)
mi_arreglo1, step = np.linspace(0, 100, num=9, retstep=True)
print(mi_arreglo1)
print(step)

[  0.   12.5  25.   37.5  50.   62.5  75.   87.5 100. ]
12.5


#### Matrices
Las matrices son arreglos bidimensionales y se crean pasando una **lista de listas** dentro de la función np.array(). Un ejemplo es el siguiente:

In [30]:
lista_de_listas = [ [1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12] ]
matriz1 = np.array(lista_de_listas)

print('matriz1:\n', matriz1)
print(f'matriz1 tiene {matriz1.ndim} dimensiones')
print(f'Su forma es: {matriz1.shape}')

matriz1:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
matriz1 tiene 2 dimensiones
Su forma es: (3, 4)


In [33]:
#crear una matriz a partir de un vector
mi_matriz = np.arange(30).reshape(-1,5)
mi_matriz

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [34]:
#redimensionar un arreglo
mi_arreglo2 = np.arange(10)
print(mi_arreglo2)
arr1 = mi_arreglo2.reshape(2,5)
print(arr1)
arr2 = mi_arreglo2.reshape(-1,5)
print(arr2)
arr3 = mi_arreglo2.reshape(5,-1)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


#### `np.zeros`

In [35]:
# Creación de un arreglo con ceros como elementos
arreglo_ceros = np.zeros(5)
print(arreglo_ceros)

[0. 0. 0. 0. 0.]


In [36]:
# Para crear un array 2D, le pasamos a la función una tupla con el número deseado de filas y columnas
arreglo_ceros_2d = np.zeros((3,5))
print(arreglo_ceros_2d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### `np.ones`

In [37]:
# Creación de un arreglo con todos uno como elementos
arreglo_unos = np.ones(3)
print(arreglo_unos)

arreglo_unos_2d = np.ones((3,5))
print(arreglo_unos_2d)

[1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [38]:
# Conocer valores máximo y mínimo de un arreglo con los métodos max() y min()
# media y desvío
arr = np.random.randint(1,20, size=(4, 5))
print(arr)
print("Máximo:", arr.max())
print("Mínimo:", arr.min())
print("Media:", arr.mean())
print("Desvío:", arr.std().round(2))

[[15 11  5  7  4]
 [10  7  3 13 10]
 [ 3  4  1 12 14]
 [ 4  1 11  2  9]]
Máximo: 15
Mínimo: 1
Media: 7.3
Desvío: 4.39


In [39]:
arr

array([[15, 11,  5,  7,  4],
       [10,  7,  3, 13, 10],
       [ 3,  4,  1, 12, 14],
       [ 4,  1, 11,  2,  9]])

In [41]:
arr.max(axis=1)

array([15, 13, 14, 11])

#### Selección de elementos mediante expresiones lógicas

In [45]:
# Creo un arreglo de 10 elementos y lo redimensiono
v=np.arange(10).reshape((2,5))*10
print(v)

# indices = (v > 50) & (v < 80) # &, and; |, or
# print(indices)

# v[indices]

indx, indy = np.where((v > 50) & (v < 80))
print(indx, indy)

# v[(indx,indy)]
print(v[indx[0],indy[0]])

#Asigno valores en las posiciones de los índices
v[(indx,indy)] = [100, 120]
v

[[ 0 10 20 30 40]
 [50 60 70 80 90]]
[1 1] [1 2]
60


array([[  0,  10,  20,  30,  40],
       [ 50, 100, 120,  80,  90]])

In [46]:
v1 = np.where(v>=100, 150, 0)
v1

array([[  0,   0,   0,   0,   0],
       [  0, 150, 150,   0,   0]])

#### Resumen de funciones, métodos y atributos de Numpy
---
✔ Funciones

`np.array([])` ➡  para crear arreglos usando listas o listas de listas

`np.random.rand(d0, d1, .., dn)` ➡ para crear arreglos de elementos aleatorios entre 0 y 1 con distribución uniforme

`np.random.randn(d0, d1, .., dn)` ➡ para crear arreglos de elementos aleatorios entre 0 y 1 con distribución normal

`np.random.randint(low=, high=, size=)` ➡ para crear arreglos de elementos aleatorios enteros

`np.arange(inicio, fin, paso)` ➡ para crear arreglos de elementos en un rango

`np.linspace(inicio, fin, num)` ➡ para crear arreglos de `num` elementos equiespaciados

`np.ones()` ➡ para crear arreglos de unos, recibe una tupla en caso de dimensión superior a 1

`np.zeros()` ➡ para crear arreglos de ceros, recibe una tupla en caso de dimensión superior a 1

`np.where(condicion)` ➡ para acceder a elementos mediante condición lógica

✔ Métodos

`arr.copy()`

`arr.reshape(a,b)`

`arr.max(axis=)`

`arr.min(axis=)`

`arr.mean(axis=)`

`arr.std(axis=)`

`arr.round(decimals=)`

✔ Atributos

`arr.shape`

`arr.ndim`

`arr.size`

#### Stacking arrays

Primero creamos algunas matrices iniciales:

In [47]:
q1 = np.full((3,4), 1.0)
q1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
q2 = np.full((4,4), 2.0)
q2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [49]:
q3 = np.full((3,4), 3.0)
q3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

#### `vstack`
Ahora los apilamos de forma vertical con `vstack`:

In [50]:
q4 = np.vstack((q1, q2, q3))
q4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [51]:
q4.shape

(10, 4)

Esto fue posible porque q1, q2 y q3 tienen todos el mismo número de columnas (las filas no son iguales, pero no pasa nada porque estamos apilando sobre ese eje).

#### `hstack`
Ahora apilamos q1 y q3 horizontalmente usando `hstack`:

In [52]:
q5 = np.hstack((q1, q3))
q5

array([[1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.]])

In [53]:
q5.shape

(3, 8)

Esto es posible porque q1 y q3 tienen 3 filas. Como q2 tiene 4 filas, no puede apilarse horizontalmente con q1 y q3:

In [54]:
try:
    q5 = np.hstack((q1, q2, q3))
except ValueError as e:
    print(e)

all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 4


## `concatenate`
La función `concatenate` apila matrices a lo largo de cualquier eje existente.

In [55]:
q7 = np.concatenate((q1, q2, q3), axis=0)  # equivalente a vstack
q7

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [56]:
q7.shape

(10, 4)

Como podrás adivinar, `hstack` es equivalente a llamar a `concatenate` con `axis=1`.

## `stack`
La función `stack` apila arrays a lo largo de un nuevo eje. Todas las matrices deben tener la misma forma.

In [57]:
q8 = np.stack((q1, q3))
q8

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]])

In [58]:
q8.shape

(2, 3, 4)

# Splitting arrays
Split es lo contrario de stack. Por ejemplo, utilicemos la función `vsplit` para dividir una matriz verticalmente.

Primero vamos a crear una matriz de 6x4:

In [59]:
r = np.arange(24).reshape(6,4)
r

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Ahora dividámoslo en tres partes iguales, verticalmente:

In [60]:
r1, r2, r3 = np.vsplit(r, 3)
r1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [61]:
r2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
r3

array([[16, 17, 18, 19],
       [20, 21, 22, 23]])

También existe una función `split` que divide un array a lo largo de cualquier eje. Llamar a `vsplit` es equivalente a llamar a `split` con `axis=0`. También existe la función `hsplit`, equivalente a llamar a `split` con `axis=1`:

In [63]:
r4, r5 = np.hsplit(r, 2)
r4

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]])

In [64]:
r5

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])